### ISSUE TITLE
Release deb packages

### ISSUE THREAD

**Issue by garaemon** [PR2/robot_self_filter#3]
Could you release deb package of robot_self_filter?

**Comment by k-okada** [comment]
+1

**Comment by wkentaro** [comment]
+100

**Comment by UltronDestroyer** [comment]
Thanks, will get to this now.
Release repository: https://github.com/pr2-gbp/robot_self_filter-gbp

**Comment by UltronDestroyer** [comment]
Pending https://github.com/ros/rosdistro/pull/9911

**Comment by UltronDestroyer** [comment]
Released https://github.com/ros/rosdistro/pull/9911#event-479238063

**Comment by wkentaro** [comment]
which branch should I send pr to? indigo-devel or master?

that seems different and master is ahead of indigo-devel.
https://github.com/PR2/robot_self_filter/commits/master
https://github.com/PR2/robot_self_filter/commits/indigo-devel

**Comment by UltronDestroyer** [comment]
indigo-devel

**Comment by wkentaro** [comment]
ok, sent pr https://github.com/PR2/robot_self_filter/pull/8
