### ISSUE TITLE
~negative param for debuging in self_filter

### ISSUE THREAD

**Issue by wkentaro** [PR2/robot_self_filter#6]
maybe useful for debugging to check what region's point clouds are filtered.

**Comment by wkentaro** [comment]
`~invert` has same feature?
https://github.com/PR2/robot_self_filter/blob/indigo-devel/include/robot_self_filter/self_see_filter.h#L117-L125

**Comment by garaemon** [comment]
`~invert` should work

**Comment by wkentaro** [comment]
Thanks. Is there place to write about it?
I mean README or something.

**Comment by wkentaro** [comment]
I found this http://wiki.ros.org/self_see_filter
