### ISSUE TITLE
Request to release new version

### ISSUE THREAD

**Issue by garaemon** [PR2/robot_self_filter#9]
Could you release newer version?

I'd like to use recently closed PRs https://github.com/PR2/robot_self_filter/pulls?q=is%3Apr+is%3Aclosed

**Comment by wkentaro** [comment]
+1

**Comment by UltronDestroyer** [comment]
Sure can my friends. Ill get to it tomorrow

**Comment by UltronDestroyer** [comment]
@wkentaro  @garaemon Do you both want administrator access to the PR2 repositories so you can make releases as well?

**Comment by wkentaro** [comment]
yeah, I'd like to.

**Comment by wkentaro** [comment]
Thanks @TheDash , but actually I don't know how to release PR2 repositories.

**Comment by UltronDestroyer** [comment]
Oh ok, Very simple.

First you need to tag a new release. You will need to clone the repo:

git clone https://github.com/PR2/robot_self_filter

Tag a release

catkin_prepare_release

Release to relase repository. All release repository can be found at https://github.com/pr2-gbp/

"bloom-release --rosdistro indigo --track indigo robot_self_filter"

and follow the command line prompts.

**Comment by wkentaro** [comment]
actually it said `remote: Permission to pr2-gbp/robot_self_filter-gbp.git denied to wkentaro.`

**Comment by UltronDestroyer** [comment]
I need to add you to pr2-gbp as well

**Comment by UltronDestroyer** [comment]
Added

**Comment by wkentaro** [comment]
it works, thanks. https://github.com/ros/rosdistro/pull/9953

**Comment by wkentaro** [comment]
https://github.com/ros/rosdistro/pull/9953 is merged, so I close this issue.

**Comment by garaemon** [comment]
> @wkentaro @garaemon Do you both want administrator access to the PR2 repositories so you can make releases as well?

Yeah, it would be great

**Comment by garaemon** [comment]
@TheDash Could you give me access to pr2-gbp? or @wkentaro can you run bloom-release?
I've just tagged new version (0.1.29)

**Comment by wkentaro** [comment]
released

**Comment by UltronDestroyer** [comment]
Yes I can, moment.

**Comment by UltronDestroyer** [comment]
Added to gbp

**Comment by garaemon** [comment]
thanks!

**Comment by trainman419** [comment]
Why so many releases? That puts an enormous load on the ROS build farm.
